server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

spring:
  data:
    mongodb:
      #      authentication-database: admin
      host: localhost
      port: 27017
      database: form


