server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

spring:
  data:
    mongodb:
      #      authentication-database: admin
      host: localhost
      port: 27017
      database: form
springUserName: admin
springPassword: 123456
systemImagesFilePath: D:\\图片\pythonLT\\images\\
randomImagesFilePath: D:\\图片\\pythonLT\\randomImages\\
articleImagesFilePath: D:\\图片\\pythonLT\\articleImages\\




